name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    #actualizar pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    # 4. Ejecutar pruebas con Pytest
    - name: Run tests
      run: |
        . venv/bin/activate
        pytest --alluredir=allure-results

    # 5. Instalar Allure CLI
    - name: Install Allure CLI
      run: |
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
        tar -xzf allure.tgz
        sudo mv allure-2.21.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    # 6. Generar el reporte Allure
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    # 7. Publicar el reporte Allure en GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
